#Config Database properties
spring:
  application:
    name: product-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productDB
    username: root
    password: 123456789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 700000
      key-frefix: rdc
    cache-names: inventory
#Set port for service
server:
  port: 8889
#  error:
#    include-stacktrace: "never"
#Config Resilence4J Circuit Breaker properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  #Config Resilence4J Circuit Breaker properties
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  #Config Resilence4J Retry properties
  retry:
    instances:
      inventory:
        registerHealthIndicator: true
        maxRetryAttempts: 10
        waitDuration: 10s
  #Config Resilence4J Timelimiter properties
  timelimiter:
    configs:
      default:
        timeoutDuration: 1000
        cancelRunningFuture: true
    instances:
      inventory:
        baseConfig: default
#Config Resilence4J Timelimiter properties
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#Config API Gateway Client properties
eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost